cms/urls.py
from django.urls import path, include
from .views import Home, EmpSignUpView, customer_login, EmpDashboard, EmpLogout, CompSignUpView, company_login, CompLogout, \
    CompDashboard, AddProfile, CompAddJob, CompJobView

app_name = 'cms'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('pu/', include([
        path('signup', EmpSignUpView.as_view(), name='emp_signup'),
        path('login', customer_login, name='emp_login'),
        path('dashboard', EmpDashboard.as_view(), name='emp_dashboard'),
        path('logout', EmpLogout.as_view(), name='emp_logout'),
        path('profile/add', AddProfile.as_view(), name='pu_add_profile'),
    ])),
    path('company/', include([
        path('signup', CompSignUpView.as_view(), name='comp_signup'),
        path('login', company_login, name='comp_login'),
        path('dashboard', CompDashboard.as_view(), name='comp_dashboard'),
        path('logout', CompLogout.as_view(), name='comp_logout'),
        path('jobs/add', CompAddJob.as_view(), name='comp_add_job'),
        path('jobs/<str:job>/detail', CompJobView.as_view(), name='comp_job_detail')
    ])),
]

hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include('cms.urls'))
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

cms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator


class User(AbstractUser):
    is_pu = models.BooleanField(default=False)
    is_company = models.BooleanField(default=False)
    organization_name = models.CharField(max_length=256)


class Company(models.Model):
    def __str__(self):
        return self.user.organization_name

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


class PU(models.Model):
    def __str__(self):
        return self.user.organization_name

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


class Profile(models.Model):
    pu = models.ForeignKey(PU, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    picture = models.ImageField()
    university = models.CharField(max_length=256)
    qualifications = models.TextField()
    skills = models.TextField()
    gpa = models.FloatField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    about = models.TextField()


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    position = models.CharField(max_length=256)
    salary = models.FloatField(default=0, validators=[MinValueValidator(0)])
    vacancy = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        return self.position.replace(' ', '_')


class ShortListCandidates(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

cms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import User, PU, Company, Profile, Job, ShortListCandidates


class EmpSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'organization_name', 'first_name', 'last_name', 'email', 'password1', 'password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_pu = True
        user.save()
        employee = PU.objects.create(user=user)
        employee.save()
        return user


class CompSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'organization_name', 'first_name', 'last_name', 'email', 'password1', 'password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_company = True
        user.save()
        company = Company.objects.create(user=user)
        company.save()
        return user


class AddProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'picture', 'qualifications', 'skills', 'gpa', 'about']


class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['position', 'salary', 'vacancy']


class ShortlistForm(forms.ModelForm):
    class Meta:
        model = ShortListCandidates
        fields = ['company', 'profile']

cms/views.py
from django.views.generic import View, CreateView, ListView, TemplateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from .models import User, Company, PU, Profile, Job, ShortListCandidates
from .forms import EmpSignUpForm, CompSignUpForm, AddProfileForm, AddJobForm, ShortlistForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .decorators import employee_required, company_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages


class Home(View):

    def get(self, request):
        return render(request, 'cms/home.html')


class EmpSignUpView(CreateView):
    model = User
    form_class = EmpSignUpForm
    template_name = 'cms/employee/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employee'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('cms:emp_dashboard')


class CompSignUpView(CreateView):
    model = User
    form_class = CompSignUpForm
    template_name = 'cms/employee/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'company'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('cms:comp_dashboard')


def customer_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("ecommerce:customer_dashboard")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request, "cms/employee/login.html", context={"form": form})


def company_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("ecommerce:customer_dashboard")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    form = AuthenticationForm()
    return render(request, "cms/company/login.html", context={"form": form})


@method_decorator([login_required, employee_required()], name='dispatch')
class EmpLogout(LogoutView):
    template_name = 'cms/employee/logout.html'

    def post(self, request, *args, **kwargs):
        logout(request)


@method_decorator([login_required, company_required()], name='dispatch')
class CompLogout(LogoutView):
    template_name = 'cms/company/logout.html'

    def post(self, request, *args, **kwargs):
        logout(request)


@method_decorator([login_required, employee_required()], name='dispatch')
class EmpDashboard(ListView):
    model = Profile
    template_name = 'cms/employee/dashboard.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        pu = self.request.user.pu
        context['pu'] = pu
        context['profiles'] = Profile.objects.filter(pu=pu)
        context['organization'] = pu.user.organization_name
        return context


@method_decorator([login_required, employee_required()], name='dispatch')
class AddProfile(CreateView):
    model = Profile
    template_name = 'cms/employee/add_complaint.html'
    form_class = AddProfileForm

    def post(self, request, *args, **kwargs):
        pu = request.user.pu
        name = request.POST['name']
        picture = request.FILES.get('picture', False)
        qualifications = request.POST['qualifications']
        skills = request.POST['skills']
        gpa = request.POST['gpa']
        about = request.POST['about']
        Profile.objects.create(pu=pu, name=name, picture=picture, university=pu.user.organization_name,
                               qualifications=qualifications,
                               skills=skills, gpa=gpa, about=about)
        return redirect('cms:emp_dashboard')


@method_decorator([login_required, company_required()], name='dispatch')
class CompDashboard(ListView):
    model = Profile
    template_name = 'cms/company/dashboard.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company'] = self.request.user.company
        context['profiles'] = Profile.objects.all()
        context['organization'] = self.request.user.organization_name
        context['jobs'] = self.request.user.company.job_set.all()
        return context


@method_decorator([login_required, company_required()], name='dispatch')
class CompAddJob(CreateView):
    model = Job
    template_name = 'cms/company/add_job.html'
    form_class = AddJobForm

    def post(self, request, *args, **kwargs):
        company = request.user.company
        if int(request.POST['salary']) > 0:
            Job.objects.create(company=company, position=request.POST['position'], salary=request.POST['salary'],
                               vacancy=request.POST['vacancy'])
        else:
            return redirect('cms:comp_add_job')
        return redirect('cms:comp_dashboard')


class CompJobView(CreateView):
    model = ShortListCandidates
    template_name = 'cms/company/job.html'
    form_class = ShortlistForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = self.request.user.company
        job = self.kwargs['job'].replace('_', ' ')
        context['company'] = company
        context['job'] = company.job_set.get(position=job)
        context['profiles'] = Profile.objects.all()
        if self.request.user.company.shortlistcandidates_set.all().exists():
            context['shortlisted'] = self.request.user.company.shortlistcandidates_set.all()
        return context

    def post(self, request, *args, **kwargs):
        company = request.user.company
        job = self.kwargs['job'].replace('_', ' ')
        profile = Profile.objects.get(name=f'{request.POST.get("name")}')
        # name = request.POST.get('name')
        # name = request.POST
        if ShortListCandidates.objects.filter(profile=profile).exists():
            return redirect('cms:comp_job_detail', job)
        else:
            a = ShortListCandidates(profile=profile, company=company)
            a.save()

templates/cms/company/add_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job</title>
</head>
<body>
<h1>Add a Job Posting</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Add</button>
</form>
</body>
</html>

templates/cms/company/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
<body>
<h1>{{ company.user.username }}'s Dashboard</h1>
<h3>Organization name : {{ organization }}</h3>
{% comment %}
<table border="1">
    <th>Name</th>
    <th>Image</th>
    <th>University</th>
    <th>Qualifications</th>
    <th>Skills</th>
    <th>GPA</th>
    <th>About</th>

    {% for profile in profiles %}
        <tr>
            <td>{{ profile.name }}</td>
            <td><img src="{{ profile.picture.url }}" alt=""></td>
            <td>{{ profile.university }}</td>
            <td>{{ profile.qualifications }}</td>
            <td>{{ profile.skills }}</td>
            <td>{{ profile.gpa }}</td>
            <td>{{ profile.about }}</td>
        </tr>
    {% empty %}
        No Profiles to show
    {% endfor %}
</table>
{% endcomment %}
<table border="1">
    <th>Position</th>
    <th>Salary</th>
    {% for job in jobs %}
        <tr>
            <td>{{ job.position }}</td>
            <td>{{ job.salary }}</td>
            <td><a href="{% url 'cms:comp_job_detail' job %}">
                <button>Details</button>
            </a></td>
        </tr>
    {% endfor %}
</table>
<br><br>
<a href="{% url 'cms:comp_add_job' %}">
    <button>Add a Job posting</button>
</a>
<br><br>
<a href="{% url 'cms:comp_logout' %}">
    <button>Logout</button>
</a>
</body>
</html>

templates/cms/company/job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job</title>
</head>
<body>
<h1>{{ company.user.organization_name }}'s job openings</h1>
<br>
<br>
<div>
    <li><b>Position : </b>{{ job.position }}</li>
    <li><b>Salary : </b>{{ job.salary }}</li>
    <li><b>Vacancies : </b>{{ job.vacancy }}</li>
</div>
<br>
<br>
<h1>Candidates available</h1>
<table border="1">
    <th>Name</th>
    <th>Image</th>
    <th>University</th>
    <th>Qualifications</th>
    <th>Skills</th>
    <th>GPA</th>
    <th>About</th>

    {% for profile in profiles %}
        <tr>
            <td>{{ profile.name }}</td>
            <td><img src="{{ profile.picture.url }}" alt=""></td>
            <td>{{ profile.university }}</td>
            <td>{{ profile.qualifications }}</td>
            <td>{{ profile.skills }}</td>
            <td>{{ profile.gpa }}</td>
            <td>{{ profile.about }}</td>
            <td>
                <form method="POST">{% csrf_token %}
                    <button name="name" value='{{ profile.name }}'>Shortlist</button>
                </form>
            </td>
        </tr>
    {% empty %}
        No Profiles to show
    {% endfor %}
</table>
<br>
<br>
<table border="1">
    <th>Name</th>
    <th>Image</th>
    <th>University</th>
    <th>Qualifications</th>
    <th>Skills</th>
    <th>GPA</th>
    <th>About</th>
    {% for shortlist in shortlisted %}
        <tr>
            <td>{{ shortlist.profile.name }}</td>
            <td><img src="{{ shortlist.profile.picture.url }}" alt=""></td>
            <td>{{ shortlist.profile.university }}</td>
            <td>{{ shortlist.profile.qualifications }}</td>
            <td>{{ shortlist.profile.skills }}</td>
            <td>{{ shortlist.profile.gpa }}</td>
            <td>{{ shortlist.profile.about }}</td>
        </tr>
    {% empty %}
        No Profiles to show
    {% endfor %}
</table>
<br>
<a href="{% url 'cms:comp_dashboard' %}">Back to Dashboard</a>
</body>
</html>

templates/cms/company/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Company Login</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="login">Login</button>
</form>
</body>
</html>

templates/cms/company/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h1>Logged out!</h1>
<a href="{% url 'cms:comp_login' %}">Login again</a>
<a href="{% url 'cms:home' %}">Back to Home</a>
</body>
</html>

templates/cms/company/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>
<h1>Company Signup</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="signup">Signup</button>
</form>
</body>
</html>